import '@/styles/globals.css'
import '@/styles/theme.css'
import type { Metadata } from 'next'

import { IconDescriptor } from 'next/dist/lib/metadata/types/metadata-types'

export interface CustomIconDescriptorType extends IconDescriptor {
  precedence?: string
}

const icon: CustomIconDescriptorType = {
  rel: 'stylesheet',
  url: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
  precedence: 'default',
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { other: icon },
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
